services:
  - type: web
    name: starring-happiness
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_NAME
      - key: DB_USER
      - key: DB_PASSWORD
      - key: DB_HOST
      - key: DB_PORT
      - key: SECRET_KEY